---
title: "R Notebook"
output: html_notebook
---

```{r}

#Tumor regions
image_int_z = fread('/home/jana/Desktop/R_dat/ZuriTumorHollowRegionMeanMarkerIntensity.csv',header = T) #ImageMeanMarkerIntensity.csv
#image_int_z = image_int_z[2:nrow(image_int_z),]
colnames(image_int_z) = unlist(lapply(strsplit(colnames(image_int_z),'_'),function(x){paste0(x[c(3,2)],collapse = ' ')}))
colnames(image_int_z)[1] = 'core'
image_int_z =image_int_z[,colnames(image_int_z)[colnames(image_int_z) %in% c(as.character(good_channels),'core')],with = F]

#For whole image
image_int_z = fread('/home/ubuntu/tmp/server_homes/janaf/Data/2019/Revisions_submission/ZTMA21_ImageMeans.csv',header = T) 
panel = fread('/home/ubuntu/tmp/server_homes/janaf/Data/2019/Revisions_submission/Data_for_submission/Basel_Zuri_StainingPanel.csv',header = T) 
panel = panel[,c('FullStack','Target')]
channels = as.numeric(unlist(lapply(str_split(names(image_int_z)[names(image_int_z) != 'core'],'_'),function(x){x[[2]]})))
targets = unique(panel[FullStack %in% channels,])
image_int_z = image_int_z[,c(names(image_int_z)[names(image_int_z) != 'core'][channels %in% panel$FullStack],'core'),with =F]
targets = targets[!duplicated(targets$FullStack),]
names(image_int_z)[names(image_int_z) != 'core'] = targets$Target
names(image_int_z)[2] = '3me Histone'
names(image_int_z)[15] = 'phospho Histone'


#Clean to match rest of R dat
test = unique(image_int_z$core)

split_core = strsplit(image_int_z$core,'_', fixed = TRUE)
image_int_z$core = unlist(lapply(split_core, function(x){paste(x[c(1,2,8,9,10)],collapse =  "_")}))

#Replace the ones that don't need acquisition number again
short = unlist(lapply(strsplit(test,'_', fixed = TRUE),function(x){paste(x[c(1,2,8,9)],collapse =  "_")}))
duplicate_idx = duplicated(short) | duplicated(short, fromLast = TRUE)
in_cores_index = unlist(lapply(unique(image_int_z$core)[duplicate_idx],function(x){which(image_int_z$core %in% x)}))
image_int_z$core[setdiff(1:length(image_int_z$core),in_cores_index)] = unlist(lapply(strsplit(image_int_z$core[setdiff(1:length(image_int_z$core),in_cores_index)],'_', fixed = TRUE), function(x){paste(x[1:length(x)-1],collapse =  "_")}))


#Exclude controls
image_int_z = image_int_z[!str_detect(image_int_z$core,'non-breast'),]

#Read in sample metadata in zurich pipeline
Sample_metadata = fread('/home/ubuntu/tmp/server_homes/janaf/Data/2019/Revisions_submission/Zuri_PatientMetadata.csv',header = T) 

#Exclude normal tissues
setkey(image_int_z,core)
setkey(Sample_metadata,core)
image_int_z = merge(image_int_z,Sample_metadata[,c('core','PID','location')],by = 'core')
image_int_z = image_int_z[!image_int_z$location == '[]',]


# maybe get rid off: Scale and censor
image_int_melted = melt.data.table(image_int_z, id.vars = c('core','PID'),measure.vars = colnames(image_int_z)[!colnames(image_int_z) %in% c('core','PID','diseasestatus','location')], variable.name = 'channel',value.name = 'value')
image_int_melted[, c_counts := bbRtools::censor_dat(value,0.99), by=channel]
image_int_melted[, c_counts_scaled := ((c_counts)/(quantile(c_counts,0.99))), by=channel]
image_int_melted[, c_counts_zscored := scale(c_counts), by=channel]

image_int_z = dcast.data.table(image_int_melted,formula = "PID + core ~ channel",value.var = "c_counts_scaled")

#Make in long format for facetting
long = melt.data.table(image_int_z,id.vars = c("PID","core","DNA1" ))
long[,norm := value / DNA1]
long[,mean_patient := mean(norm), by = c('variable','PID')]
long[,diff_patient := mean_patient - norm]
long[,overall_mean := mean(diff_patient), by = 'variable']
long[,overall_std := pracma::std(diff_patient), by = 'variable']
long$variable = as.character(long$variable)



pdf('/home/jana/Desktop/R_dat/test.pdf', width = 10, height = 10)
par(mfrow=c(4,7))
for (i in unique(long$variable)){
  cur = long[variable ==i,]
  print(ggplot(cur,aes(x = mean_patient,y = diff_patient))+
  geom_point()+
  geom_hline(yintercept= cur$overall_mean, linetype="dashed", color = "red")+
  geom_hline(yintercept= cur$overall_mean + 1.96 * cur$overall_std, linetype="dashed", color = "blue")+
  geom_hline(yintercept= cur$overall_mean - 1.96 * cur$overall_std, linetype="dashed", color = "blue")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
    ggtitle(i))
}
dev.off()







```

#B and A plots for psoitive cells only
```{r}

dat = dat[!str_detect(dat$core,'control'),]
dat = dat[!str_detect(dat$core,'non-breast'),]

# #maybe exclude after matching
dat = dat[!str_detect(dat$core,regex('Ay.x1')),]
dat = dat[!str_detect(dat$core,regex('Ay..x1')),]
dat[,c_counts := bbRtools::censor_dat(mc_counts,0.99),by = channel]
dat[,c_counts_norm := c_counts/quantile(c_counts,0.99),by = channel]

#ER
datER = dat[channel == '112475Gd156Di Estroge',]
datER = unique(datER)
datER[,ncells := .N,by = 'core']
datER = merge(datER,unique(Sample_metadata[,c('core','patientcode')]),by = 'core')

ggplot(datER,aes(x = c_counts_norm))+
  geom_density()

#only pos
datER = datER[c_counts_norm > 0.25,]
datER[,ncells_pos := .N,by = 'core']


datER[,mean_core := mean(c_counts_norm),by = 'core']
datER = unique(datER[,c('patientcode','core','mean_core','ncells','ncells_pos')])

#datER[,mean_core := mean_core/ncells]
 datER = datER[ncells > 200,]


datER[,mean_patient := mean(mean_core), by = c('patientcode')]
datER[,diff_patient := mean_patient - mean_core]
datER[,overall_mean := mean(diff_patient)]
datER[,overall_std := pracma::std(diff_patient)]


prcnt = (length(which(datER$diff_patient > datER$overall_mean + 1.96 * datER$overall_std)) + length(which(datER$diff_patient < datER$overall_mean - 1.96 * datER$overall_std)))/nrow(datER)


g = ggplot(datER,aes(x = mean_patient,y = diff_patient))+
  geom_point()+
  geom_hline(yintercept= datER$overall_mean, linetype="dashed", color = "red")+
  geom_hline(yintercept= datER$overall_mean + 1.96 * datER$overall_std, linetype="dashed", color = "blue")+
  geom_hline(yintercept= datER$overall_mean - 1.96 * datER$overall_std, linetype="dashed", color = "blue")+
  ylim(-0.4,0.4)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
    ggtitle(paste0('ER_%',as.character(prcnt)))




pdf('/home/jana/Desktop/R_dat/ERpos_200.pdf', width = 10, height = 10)
g
dev.off()


#PR
datER = dat[channel == '312878Gd158Di Progest',]
datER = unique(datER)
datER[,ncells := .N,by = 'core']
datER = merge(datER,unique(Sample_metadata[,c('core','patientcode')]),by = 'core')

ggplot(datER,aes(x = c_counts_norm))+
  geom_density()

#only pos
datER = datER[c_counts_norm > 0.29,]
datER[,ncells_pos := .N,by = 'core']


datER[,mean_core := mean(c_counts_norm),by = 'core']
datER = unique(datER[,c('patientcode','core','mean_core','ncells','ncells_pos')])

#datER[,mean_core := mean_core/ncells]
datER = datER[ncells > 200,]

datER[,mean_patient := mean(mean_core), by = c('patientcode')]
datER[,diff_patient := mean_patient - mean_core]
datER[,overall_mean := mean(diff_patient)]
datER[,overall_std := pracma::std(diff_patient)]


prcnt = (length(which(datER$diff_patient > datER$overall_mean + 1.96 * datER$overall_std)) + length(which(datER$diff_patient < datER$overall_mean - 1.96 * datER$overall_std)))/nrow(datER)

g = ggplot(datER,aes(x = mean_patient,y = diff_patient))+
  geom_point()+
  geom_hline(yintercept= datER$overall_mean, linetype="dashed", color = "red")+
  geom_hline(yintercept= datER$overall_mean + 1.96 * datER$overall_std, linetype="dashed", color = "blue")+
  geom_hline(yintercept= datER$overall_mean - 1.96 * datER$overall_std, linetype="dashed", color = "blue")+
  ylim(-0.4,0.4)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
    ggtitle(paste0('PR_%',as.character(prcnt)))




pdf('/home/jana/Desktop/R_dat/PRpos_200.pdf', width = 10, height = 10)
g
dev.off()


#HER2
datER = dat[channel == '201487Eu151Di cerbB',]
datER = unique(datER)
datER[,ncells := .N,by = 'core']
datER = merge(datER,unique(Sample_metadata[,c('core','patientcode')]),by = 'core')

ggplot(datER,aes(x = c_counts_norm))+
  geom_density()

#only pos
datER = datER[c_counts_norm > 0.25,]
datER[,ncells_pos := .N,by = 'core']


datER[,mean_core := mean(c_counts_norm),by = 'core']
datER = unique(datER[,c('patientcode','core','mean_core','ncells','ncells_pos')])

#datER[,mean_core := mean_core/ncells]
datER = datER[ncells > 200,]

datER[,mean_patient := mean(mean_core), by = c('patientcode')]
datER[,diff_patient := mean_patient - mean_core]
datER[,overall_mean := mean(diff_patient)]
datER[,overall_std := pracma::std(diff_patient)]

prcnt = (length(which(datER$diff_patient > datER$overall_mean + 1.96 * datER$overall_std)) + length(which(datER$diff_patient < datER$overall_mean - 1.96 * datER$overall_std)))/nrow(datER)


g = ggplot(datER,aes(x = mean_patient,y = diff_patient))+
  geom_point()+
  geom_hline(yintercept= datER$overall_mean, linetype="dashed", color = "red")+
  geom_hline(yintercept= datER$overall_mean + 1.96 * datER$overall_std, linetype="dashed", color = "blue")+
  geom_hline(yintercept= datER$overall_mean - 1.96 * datER$overall_std, linetype="dashed", color = "blue")+
  ylim(-0.4,0.4)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
    ggtitle(paste0('HER2_%',as.character(prcnt)))



pdf('/home/jana/Desktop/R_dat/HER2pos_200.pdf', width = 10, height = 10)
g
dev.off()



#Ki67
datER = dat[channel == '1441101Er168Di Ki67',]
datER = unique(datER)
datER[,ncells := .N,by = 'core']
datER = merge(datER,unique(Sample_metadata[,c('core','patientcode')]),by = 'core')

ggplot(datER,aes(x = c_counts_norm))+
  geom_density()

#only pos
datER = datER[c_counts_norm > 0.09,]
datER[,ncells_pos := .N,by = 'core']


datER[,mean_core := mean(c_counts_norm),by = 'core']
datER = unique(datER[,c('patientcode','core','mean_core','ncells','ncells_pos')])

#datER[,mean_core := mean_core/ncells]
datER = datER[ncells > 200,]

datER[,mean_patient := mean(mean_core), by = c('patientcode')]
datER[,diff_patient := mean_patient - mean_core]
datER[,overall_mean := mean(diff_patient)]
datER[,overall_std := pracma::std(diff_patient)]

prcnt = (length(which(datER$diff_patient > datER$overall_mean + 1.96 * datER$overall_std)) + length(which(datER$diff_patient < datER$overall_mean - 1.96 * datER$overall_std)))/nrow(datER)

g = ggplot(datER,aes(x = mean_patient,y = diff_patient))+
  geom_point()+
  geom_hline(yintercept= datER$overall_mean, linetype="dashed", color = "red")+
  geom_hline(yintercept= datER$overall_mean + 1.96 * datER$overall_std, linetype="dashed", color = "blue")+
  geom_hline(yintercept= datER$overall_mean - 1.96 * datER$overall_std, linetype="dashed", color = "blue")+
  ylim(-0.4,0.4)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
    ggtitle(paste0('Ki67_%',as.character(prcnt)))



pdf('/home/jana/Desktop/R_dat/Ki67pos_200.pdf', width = 10, height = 10)
g
dev.off()



#Ecadh
datER = dat[channel == '1031747Er167Di ECadhe',]
datER = unique(datER)
datER[,ncells := .N,by = 'core']
datER = merge(datER,unique(Sample_metadata[,c('core','patientcode')]),by = 'core')

ggplot(datER,aes(x = c_counts_norm))+
  geom_density()

#only pos
datER = datER[c_counts_norm > 0.75,]
datER[,ncells_pos := .N,by = 'core']


datER[,mean_core := mean(c_counts_norm),by = 'core']
datER = unique(datER[,c('patientcode','core','mean_core','ncells','ncells_pos')])

#datER[,mean_core := mean_core/ncells]
datER = datER[ncells > 200,]

datER[,mean_patient := mean(mean_core), by = c('patientcode')]
datER[,diff_patient := mean_patient - mean_core]
datER[,overall_mean := mean(diff_patient)]
datER[,overall_std := pracma::std(diff_patient)]

prcnt = (length(which(datER$diff_patient > datER$overall_mean + 1.96 * datER$overall_std)) + length(which(datER$diff_patient < datER$overall_mean - 1.96 * datER$overall_std)))/nrow(datER)

g = ggplot(datER,aes(x = mean_patient,y = diff_patient))+
  geom_point()+
  geom_hline(yintercept= datER$overall_mean, linetype="dashed", color = "red")+
  geom_hline(yintercept= datER$overall_mean + 1.96 * datER$overall_std, linetype="dashed", color = "blue")+
  geom_hline(yintercept= datER$overall_mean - 1.96 * datER$overall_std, linetype="dashed", color = "blue")+
  ylim(-0.4,0.4)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
    ggtitle(paste0('Ecadh_%',as.character(prcnt)))




pdf('/home/jana/Desktop/R_dat/Ecadhpos_200.pdf', width = 10, height = 10)
g
dev.off()






```

